import { prisma } from "@/lib/prisma";

const skillCategories = [
  {
    name: "Programming Languages",
    key: "languages",
    description: "Programming and scripting languages",
    displayOrder: 1,
    skills: [
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Python",
      "Java",
      "C#",
      "C++",
      "C",
      "PHP",
      "Ruby",
      "Go",
      "Rust",
      "Swift",
      "Kotlin",
      "Scala",
      "R",
      "MATLAB",
      "Perl",
      "Dart",
      "Elixir",
      "Haskell",
      "Lua",
      "Shell Script",
      "Bash",
      "PowerShell",
      "SQL",
      "GraphQL",
      "Objective-C",
      "Assembly",
      "COBOL",
      "Fortran",
      "Julia",
      "Groovy",
      "F#",
      "Clojure",
      "Erlang",
    ],
  },
  {
    name: "Frameworks & Libraries",
    key: "frameworks",
    description: "Frontend, backend, and testing frameworks",
    displayOrder: 2,
    skills: [
      // Frontend
      "React",
      "Next.js",
      "Vue.js",
      "Nuxt.js",
      "Angular",
      "Svelte",
      "SvelteKit",
      "Solid.js",
      "Qwik",
      "Remix",
      "Astro",
      "Gatsby",
      "Ember.js",
      "Backbone.js",
      "Alpine.js",
      "Preact",
      // Backend
      "Node.js",
      "Express.js",
      "NestJS",
      "Fastify",
      "Koa",
      "Hapi",
      "Django",
      "Flask",
      "FastAPI",
      "Spring Boot",
      "Spring Framework",
      "ASP.NET Core",
      ".NET Framework",
      "Ruby on Rails",
      "Laravel",
      "Symfony",
      "CodeIgniter",
      "Gin",
      "Echo",
      "Fiber",
      "Actix",
      "Rocket",
      // Mobile
      "React Native",
      "Flutter",
      "Ionic",
      "Xamarin",
      "Cordova",
      "Capacitor",
      "SwiftUI",
      "UIKit",
      "Jetpack Compose",
      // Testing
      "Jest",
      "Vitest",
      "Mocha",
      "Chai",
      "Jasmine",
      "Cypress",
      "Playwright",
      "Selenium",
      "Puppeteer",
      "Testing Library",
      "JUnit",
      "TestNG",
      "PyTest",
      "RSpec",
      "PHPUnit",
    ],
  },
  {
    name: "Databases & ORMs",
    key: "databases",
    description: "SQL, NoSQL databases and ORMs",
    displayOrder: 3,
    skills: [
      // SQL
      "PostgreSQL",
      "MySQL",
      "MariaDB",
      "SQLite",
      "Microsoft SQL Server",
      "Oracle Database",
      "Amazon Aurora",
      "CockroachDB",
      // NoSQL
      "MongoDB",
      "Redis",
      "Cassandra",
      "DynamoDB",
      "Couchbase",
      "CouchDB",
      "Neo4j",
      "ArangoDB",
      "Firebase Firestore",
      "Supabase",
      // Time Series
      "InfluxDB",
      "TimescaleDB",
      "Prometheus",
      // Search
      "Elasticsearch",
      "Solr",
      "Algolia",
      "Meilisearch",
      "Typesense",
      // Vector
      "Pinecone",
      "Weaviate",
      "Qdrant",
      "Milvus",
      "Chroma",
      // ORMs
      "Prisma",
      "TypeORM",
      "Sequelize",
      "Drizzle ORM",
      "Mongoose",
      "SQLAlchemy",
      "Django ORM",
      "Hibernate",
      "Entity Framework",
      "Entity Framework Core",
      "Dapper",
      "Knex.js",
      "Kysely",
      "ActiveRecord",
      "Eloquent",
      "Doctrine",
      "GORM",
      "Ent",
      "Diesel",
      "SeaORM",
    ],
  },
  {
    name: "Tools & Technologies",
    key: "tools",
    description: "Development tools, IDEs, and utilities",
    displayOrder: 4,
    skills: [
      // Version Control
      "Git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "SVN",
      "Mercurial",
      // CI/CD
      "Jenkins",
      "GitHub Actions",
      "GitLab CI",
      "CircleCI",
      "Travis CI",
      "Azure DevOps",
      "TeamCity",
      "Bamboo",
      "ArgoCD",
      "Flux",
      // Containers
      "Docker",
      "Kubernetes",
      "Docker Compose",
      "Podman",
      "Helm",
      "Rancher",
      "OpenShift",
      // Build Tools
      "Webpack",
      "Vite",
      "Rollup",
      "Parcel",
      "esbuild",
      "Turbopack",
      "Gradle",
      "Maven",
      "Ant",
      "Make",
      "CMake",
      "Bazel",
      // Package Managers
      "npm",
      "yarn",
      "pnpm",
      "pip",
      "poetry",
      "composer",
      "bundler",
      "cargo",
      "go mod",
      // IDEs
      "VS Code",
      "IntelliJ IDEA",
      "WebStorm",
      "PyCharm",
      "Eclipse",
      "NetBeans",
      "Sublime Text",
      "Vim",
      "Emacs",
      "Xcode",
      "Android Studio",
      // API Tools
      "Postman",
      "Insomnia",
      "Swagger",
      "GraphQL Playground",
      "REST Client",
      // Monitoring
      "Datadog",
      "New Relic",
      "Grafana",
      "Prometheus",
      "ELK Stack",
      "Splunk",
      "Sentry",
      "LogRocket",
      "Kibana",
      // Project Management
      "Jira",
      "Confluence",
      "Trello",
      "Asana",
      "Linear",
      "Monday.com",
      "ClickUp",
      // Design
      "Figma",
      "Adobe XD",
      "Sketch",
      "InVision",
      "Zeplin",
      "Framer",
    ],
  },
  {
    name: "Cloud Platforms",
    key: "cloud",
    description: "Cloud services and infrastructure",
    displayOrder: 5,
    skills: [
      // AWS
      "AWS",
      "Amazon EC2",
      "Amazon S3",
      "AWS Lambda",
      "Amazon RDS",
      "Amazon DynamoDB",
      "Amazon CloudFront",
      "AWS ECS",
      "AWS EKS",
      "Amazon SQS",
      "Amazon SNS",
      "AWS CloudFormation",
      "AWS CDK",
      "Amazon API Gateway",
      "AWS Amplify",
      "Amazon Cognito",
      "AWS Step Functions",
      "Amazon EventBridge",
      // Azure
      "Microsoft Azure",
      "Azure Functions",
      "Azure App Service",
      "Azure SQL Database",
      "Azure Cosmos DB",
      "Azure Blob Storage",
      "Azure DevOps",
      "Azure Kubernetes Service",
      "Azure Active Directory",
      // GCP
      "Google Cloud Platform",
      "Google Compute Engine",
      "Google Cloud Storage",
      "Google Cloud Functions",
      "Google Cloud Run",
      "Google Kubernetes Engine",
      "Firebase",
      "Google BigQuery",
      "Google Cloud SQL",
      "Google Pub/Sub",
      // Other
      "DigitalOcean",
      "Heroku",
      "Vercel",
      "Netlify",
      "Cloudflare",
      "Cloudflare Workers",
      "Railway",
      "Render",
      "Fly.io",
      "Supabase",
      "PlanetScale",
      "Neon",
      // IaC
      "Terraform",
      "Pulumi",
      "CloudFormation",
      "Ansible",
      "Chef",
      "Puppet",
    ],
  },
  {
    name: "Methodologies & Practices",
    key: "methodologies",
    description: "Development methodologies and best practices",
    displayOrder: 6,
    skills: [
      // Methodologies
      "Agile",
      "Scrum",
      "Kanban",
      "Waterfall",
      "Lean",
      "DevOps",
      "CI/CD",
      "Test-Driven Development (TDD)",
      "Behavior-Driven Development (BDD)",
      "Domain-Driven Design (DDD)",
      "Microservices Architecture",
      "Monolithic Architecture",
      "Event-Driven Architecture",
      "Serverless Architecture",
      "RESTful API Design",
      "GraphQL API Design",
      "SOLID Principles",
      "Design Patterns",
      "Clean Code",
      "Code Review",
      "Pair Programming",
      "Mob Programming",
      // Practices
      "Version Control",
      "Continuous Integration",
      "Continuous Deployment",
      "Continuous Delivery",
      "Infrastructure as Code",
      "Configuration Management",
      "Monitoring & Logging",
      "Performance Optimization",
      "Security Best Practices",
      "Accessibility (a11y)",
      "Responsive Design",
      "Mobile-First Design",
      "Progressive Web Apps (PWA)",
      "Single Page Applications (SPA)",
      "Server-Side Rendering (SSR)",
      "Static Site Generation (SSG)",
      // Project Management
      "Sprint Planning",
      "Backlog Grooming",
      "Daily Standups",
      "Retrospectives",
      "User Story Mapping",
      "Estimation",
      "Risk Management",
      "Stakeholder Management",
    ],
  },
  {
    name: "Data Science & ML",
    key: "dataScience",
    description: "Machine learning and data science tools",
    displayOrder: 7,
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Data Analysis",
      "Data Visualization",
      "Statistical Analysis",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "Matplotlib",
      "Seaborn",
      "Jupyter Notebook",
      "Apache Spark",
      "Hadoop",
      "Tableau",
      "Power BI",
      "Keras",
      "XGBoost",
      "LightGBM",
    ],
  },
  {
    name: "Blockchain",
    key: "blockchain",
    description: "Blockchain and Web3 technologies",
    displayOrder: 8,
    skills: [
      "Blockchain",
      "Ethereum",
      "Solidity",
      "Smart Contracts",
      "Web3.js",
      "Ethers.js",
      "Hardhat",
      "Truffle",
      "IPFS",
      "Bitcoin",
      "Hyperledger",
      "Polygon",
      "Solana",
      "Rust (Solana)",
    ],
  },
  {
    name: "Security",
    key: "security",
    description: "Cybersecurity and application security",
    displayOrder: 9,
    skills: [
      "Cybersecurity",
      "Penetration Testing",
      "OWASP",
      "OAuth",
      "JWT",
      "SSL/TLS",
      "Encryption",
      "Authentication",
      "Authorization",
      "Security Auditing",
      "Vulnerability Assessment",
      "Network Security",
      "Application Security",
    ],
  },
  {
    name: "Mobile Development",
    key: "mobile",
    description: "Mobile app development platforms",
    displayOrder: 10,
    skills: [
      "iOS Development",
      "Android Development",
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Objective-C",
      "Java (Android)",
      "Xcode",
      "Android Studio",
      "App Store Optimization",
      "Mobile UI/UX",
    ],
  },
  {
    name: "UI/UX Design",
    key: "uiux",
    description: "User interface and experience design",
    displayOrder: 11,
    skills: [
      "UI/UX Design",
      "User Research",
      "Wireframing",
      "Prototyping",
      "User Testing",
      "Information Architecture",
      "Interaction Design",
      "Visual Design",
      "Design Systems",
      "Accessibility Design",
      "Responsive Design",
      "Mobile Design",
    ],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Clear existing skills and categories
  console.log("🗑️  Clearing existing data...");
  await prisma.skill.deleteMany();
  await prisma.skillCategory.deleteMany();

  // Seed skill categories and skills
  console.log("📦 Seeding skill categories and skills...");

  for (const category of skillCategories) {
    const { skills, ...categoryData } = category;

    const createdCategory = await prisma.skillCategory.create({
      data: categoryData,
    });

    console.log(`✅ Created category: ${createdCategory.name}`);

    // Create skills for this category
    const skillsData = skills.map((skillName) => ({
      name: skillName,
      categoryId: createdCategory.id,
    }));

    await prisma.skill.createMany({
      data: skillsData,
    });

    console.log(`   ✅ Added ${skills.length} skills`);
  }

  // Get total counts
  const categoryCount = await prisma.skillCategory.count();
  const skillCount = await prisma.skill.count();

  console.log("\n✨ Seed completed successfully!");
  console.log(`📊 Total categories: ${categoryCount}`);
  console.log(`📊 Total skills: ${skillCount}`);
}

main()
  .catch((e) => {
    console.error("❌ Error during seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
