/**
 * Comprehensive skill suggestions for resume autocomplete
 * Curated from popular tech stacks, job postings, and industry standards
 */

export const skillSuggestions = {
  languages: [
    // Web Languages
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Python",
    "Java",
    "C#",
    "C++",
    "C",
    "PHP",
    "Ruby",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    "Perl",
    "Dart",
    "Elixir",
    "Haskell",
    "Lua",
    "Shell Script",
    "Bash",
    "PowerShell",
    "SQL",
    "GraphQL",
    "Objective-C",
    "Assembly",
    "COBOL",
    "Fortran",
    "Julia",
    "Groovy",
    "F#",
    "Clojure",
    "Erlang",
  ],

  frameworks: [
    // Frontend Frameworks
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "SvelteKit",
    "Solid.js",
    "Qwik",
    "Remix",
    "Astro",
    "Gatsby",
    "Ember.js",
    "Backbone.js",
    "Alpine.js",
    "Preact",
    
    // Backend Frameworks
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Hapi",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring Framework",
    "ASP.NET Core",
    ".NET Framework",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Rocket",
    
    // Mobile Frameworks
    "React Native",
    "Flutter",
    "Ionic",
    "Xamarin",
    "Cordova",
    "Capacitor",
    "SwiftUI",
    "UIKit",
    "Jetpack Compose",
    
    // Testing Frameworks
    "Jest",
    "Vitest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Cypress",
    "Playwright",
    "Selenium",
    "Puppeteer",
    "Testing Library",
    "JUnit",
    "TestNG",
    "PyTest",
    "RSpec",
    "PHPUnit",
  ],

  databases: [
    // SQL Databases
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "SQLite",
    "Microsoft SQL Server",
    "Oracle Database",
    "Amazon Aurora",
    "CockroachDB",
    
    // NoSQL Databases
    "MongoDB",
    "Redis",
    "Cassandra",
    "DynamoDB",
    "Couchbase",
    "CouchDB",
    "Neo4j",
    "ArangoDB",
    "Firebase Firestore",
    "Supabase",
    
    // Time Series
    "InfluxDB",
    "TimescaleDB",
    "Prometheus",
    
    // Search Engines
    "Elasticsearch",
    "Solr",
    "Algolia",
    "Meilisearch",
    "Typesense",
    
    // Graph Databases
    "Neo4j",
    "Amazon Neptune",
    "ArangoDB",
    
    // Vector Databases
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "Milvus",
    "Chroma",
    
    // ORMs & Query Builders
    "Prisma",
    "TypeORM",
    "Sequelize",
    "Drizzle ORM",
    "Mongoose",
    "SQLAlchemy",
    "Django ORM",
    "Hibernate",
    "Entity Framework",
    "Entity Framework Core",
    "Dapper",
    "Knex.js",
    "Kysely",
    "ActiveRecord",
    "Eloquent",
    "Doctrine",
    "GORM",
    "Ent",
    "Diesel",
    "SeaORM",
  ],

  tools: [
    // Version Control
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    
    // CI/CD
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Azure DevOps",
    "TeamCity",
    "Bamboo",
    "ArgoCD",
    "Flux",
    
    // Containerization & Orchestration
    "Docker",
    "Kubernetes",
    "Docker Compose",
    "Podman",
    "Helm",
    "Rancher",
    "OpenShift",
    
    // Build Tools
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "esbuild",
    "Turbopack",
    "Gradle",
    "Maven",
    "Ant",
    "Make",
    "CMake",
    "Bazel",
    
    // Package Managers
    "npm",
    "yarn",
    "pnpm",
    "pip",
    "poetry",
    "composer",
    "bundler",
    "cargo",
    "go mod",
    
    // IDEs & Editors
    "VS Code",
    "IntelliJ IDEA",
    "WebStorm",
    "PyCharm",
    "Eclipse",
    "NetBeans",
    "Sublime Text",
    "Vim",
    "Emacs",
    "Xcode",
    "Android Studio",
    
    // API Tools
    "Postman",
    "Insomnia",
    "Swagger",
    "GraphQL Playground",
    "REST Client",
    
    // Monitoring & Logging
    "Datadog",
    "New Relic",
    "Grafana",
    "Prometheus",
    "ELK Stack",
    "Splunk",
    "Sentry",
    "LogRocket",
    "Kibana",
    
    // Project Management
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Linear",
    "Monday.com",
    "ClickUp",
    
    // Design Tools
    "Figma",
    "Adobe XD",
    "Sketch",
    "InVision",
    "Zeplin",
    "Framer",
  ],

  cloud: [
    // AWS Services
    "AWS",
    "Amazon EC2",
    "Amazon S3",
    "AWS Lambda",
    "Amazon RDS",
    "Amazon DynamoDB",
    "Amazon CloudFront",
    "AWS ECS",
    "AWS EKS",
    "Amazon SQS",
    "Amazon SNS",
    "AWS CloudFormation",
    "AWS CDK",
    "Amazon API Gateway",
    "AWS Amplify",
    "Amazon Cognito",
    "AWS Step Functions",
    "Amazon EventBridge",
    
    // Azure Services
    "Microsoft Azure",
    "Azure Functions",
    "Azure App Service",
    "Azure SQL Database",
    "Azure Cosmos DB",
    "Azure Blob Storage",
    "Azure DevOps",
    "Azure Kubernetes Service",
    "Azure Active Directory",
    
    // Google Cloud Services
    "Google Cloud Platform",
    "Google Compute Engine",
    "Google Cloud Storage",
    "Google Cloud Functions",
    "Google Cloud Run",
    "Google Kubernetes Engine",
    "Firebase",
    "Google BigQuery",
    "Google Cloud SQL",
    "Google Pub/Sub",
    
    // Other Cloud Providers
    "DigitalOcean",
    "Heroku",
    "Vercel",
    "Netlify",
    "Cloudflare",
    "Cloudflare Workers",
    "Railway",
    "Render",
    "Fly.io",
    "Supabase",
    "PlanetScale",
    "Neon",
    
    // Infrastructure as Code
    "Terraform",
    "Pulumi",
    "CloudFormation",
    "Ansible",
    "Chef",
    "Puppet",
  ],

  methodologies: [
    // Development Methodologies
    "Agile",
    "Scrum",
    "Kanban",
    "Waterfall",
    "Lean",
    "DevOps",
    "CI/CD",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Domain-Driven Design (DDD)",
    "Microservices Architecture",
    "Monolithic Architecture",
    "Event-Driven Architecture",
    "Serverless Architecture",
    "RESTful API Design",
    "GraphQL API Design",
    "SOLID Principles",
    "Design Patterns",
    "Clean Code",
    "Code Review",
    "Pair Programming",
    "Mob Programming",
    
    // Software Engineering Practices
    "Version Control",
    "Continuous Integration",
    "Continuous Deployment",
    "Continuous Delivery",
    "Infrastructure as Code",
    "Configuration Management",
    "Monitoring & Logging",
    "Performance Optimization",
    "Security Best Practices",
    "Accessibility (a11y)",
    "Responsive Design",
    "Mobile-First Design",
    "Progressive Web Apps (PWA)",
    "Single Page Applications (SPA)",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    
    // Project Management
    "Sprint Planning",
    "Backlog Grooming",
    "Daily Standups",
    "Retrospectives",
    "User Story Mapping",
    "Estimation",
    "Risk Management",
    "Stakeholder Management",
  ],
};

// Additional specialized skills
export const specializedSkills = {
  dataScience: [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Data Analysis",
    "Data Visualization",
    "Statistical Analysis",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Jupyter Notebook",
    "Apache Spark",
    "Hadoop",
    "Tableau",
    "Power BI",
    "Keras",
    "XGBoost",
    "LightGBM",
  ],

  blockchain: [
    "Blockchain",
    "Ethereum",
    "Solidity",
    "Smart Contracts",
    "Web3.js",
    "Ethers.js",
    "Hardhat",
    "Truffle",
    "IPFS",
    "Bitcoin",
    "Hyperledger",
    "Polygon",
    "Solana",
    "Rust (Solana)",
  ],

  security: [
    "Cybersecurity",
    "Penetration Testing",
    "OWASP",
    "OAuth",
    "JWT",
    "SSL/TLS",
    "Encryption",
    "Authentication",
    "Authorization",
    "Security Auditing",
    "Vulnerability Assessment",
    "Network Security",
    "Application Security",
  ],

  mobile: [
    "iOS Development",
    "Android Development",
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Objective-C",
    "Java (Android)",
    "Xcode",
    "Android Studio",
    "App Store Optimization",
    "Mobile UI/UX",
  ],

  uiux: [
    "UI/UX Design",
    "User Research",
    "Wireframing",
    "Prototyping",
    "User Testing",
    "Information Architecture",
    "Interaction Design",
    "Visual Design",
    "Design Systems",
    "Accessibility Design",
    "Responsive Design",
    "Mobile Design",
  ],
};

// Combine all skills for search
export const allSkills = [
  ...skillSuggestions.languages,
  ...skillSuggestions.frameworks,
  ...skillSuggestions.databases,
  ...skillSuggestions.tools,
  ...skillSuggestions.cloud,
  ...skillSuggestions.methodologies,
  ...specializedSkills.dataScience,
  ...specializedSkills.blockchain,
  ...specializedSkills.security,
  ...specializedSkills.mobile,
  ...specializedSkills.uiux,
];
